No exceptions occurred
Inside finally block
Test completed.
